#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlattice_py
  
  rm -rf build/* myData/* myU1/* myU2/* tmp/* 
  
  pySloc -L py scripts/genNodeID1 scripts/genNodeID3 uConsolidate uReStruc uStats verifyContentKeys  -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
