#!/usr/bin/env bash

cd $DEV_BASE/py/xlattice_py

rm -rf build/* myData/* myU1/* myU2/*  tmp/*

pySloc -X dist -X myData -X myU1 -X myU2 -v  $@ \
    txt:openssl*        \
    txt:MANIFEST.in \
    txt:.gitignore \
    bash:auto8it bash:countem bash:installit    \
    bash:makeMoreNodeIDs bash:test.all          \
    py:uConsolidate py:uPreen py:uStats         \
    py:scripts/genNodeID1 py:scripts/genNodeID3 \
    py:verifyContentKeys                        \



