#!/bin/bash

# USE THIS FILE ONLY TO GET COUNTS
# dev0-3/U0 - USING OTHER VALUES
echo '' > moreNodeIDs
scripts/genNodeID -s 05 >>moreNodeIDs
scripts/genNodeID -s 06 >>moreNodeIDs
scripts/genNodeID -s 07 >>moreNodeIDs
scripts/genNodeID -s 08 >>moreNodeIDs

# /var/U, U0
scripts/genNodeID -s 09 >>moreNodeIDs
scripts/genNodeID -s 0a >>moreNodeIDs

# /var/Udoc, Udoc0
scripts/genNodeID -s 0b >>moreNodeIDs
scripts/genNodeID -s 0c >>moreNodeIDs

# /var/Ue
scripts/genNodeID -s 0d >>moreNodeIDs

# losgatos U, U0
scripts/genNodeID -s 0e >>moreNodeIDs
scripts/genNodeID -s 0f >>moreNodeIDs

# guadalupe U, U0
scripts/genNodeID -s 10 >>moreNodeIDs
scripts/genNodeID -s 11 >>moreNodeIDs

# node2 U, U0
scripts/genNodeID -s 12 >>moreNodeIDs
scripts/genNodeID -s 13 >>moreNodeIDs

# supermicro U, U0
scripts/genNodeID -s 14 >>moreNodeIDs
scripts/genNodeID -s 15 >>moreNodeIDs

# magick U, U0
scripts/genNodeID -s 16 >>moreNodeIDs
scripts/genNodeID -s 17 >>moreNodeIDs

# grace U, U0
scripts/genNodeID -s 18 >>moreNodeIDs
scripts/genNodeID -s 19 >>moreNodeIDs

# spares
scripts/genNodeID -s 1a >>moreNodeIDs
scripts/genNodeID -s 1b >>moreNodeIDs
scripts/genNodeID -s 1c >>moreNodeIDs
scripts/genNodeID -s 1d >>moreNodeIDs
