#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlattice_py
  
  autopep8 -air xlattice 
  autopep8 -air xlattice/u 
  autopep8 -air u_consolidate u_preen u_stats verify_content_keys *.py
  echo "not styling extsrc/ subdir"
  echo "not styling logs/ subdir"
  echo "not styling scripts/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
