#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlattice_py
  
  autopep8 -ai -r xlattice 
  autopep8 -air xlattice/u 
  autopep8 -ai gen_node_id u_consolidate u_preen u_re_struc u_stats verify_content_keys *.py
  echo "not styling extsrc/ subdir"
  echo "not styling logs/ subdir"
  echo "not styling scripts/ subdir"
  echo "not styling sha-3bytetestvectors/ subdir"
  echo "not styling shabytetestvectors/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
