#!/usr/bin/python3

# ~/dev/py/xlattice_py/uReStruc

import os
import stat
import sys
from argparse import ArgumentParser

from xlattice import (__version__, __version_date__)
from xlattice.stats import collectStats
from xlattice.u     import (DIR_FLAT, DIR16x16, DIR256x256,
                        DIR_STRUC_NAMES,
                        UDir, nameToDirStruc, dirStrucToName)

def reStructureUDir(options):

    newStruc = options.newStruc
    newStrucName = options.newStrucName
    oldStruc = options.oldStruc
    oldStrucName = options.oldStrucName

    outPath = options.outPath
    uDir = options.uDir
    verbose = options.verbose

    outDir  = None              # surrogate for boolen
    if outPath:             
        outDir = UDir(outPath, dirStruc=newStruc)

def main():

    # program defaults ----------------------------------------------

    # parse the command line ----------------------------------------
    DESC = 'modify directory structure for uDir, optionally copying it to another directory (UPATH)'
    
    parser = ArgumentParser(description=DESC)

    parser.add_argument('-j', '--justShow', action='store_true',
                        help='show options and exit')

    parser.add_argument('-o', '--outPath', type=str,
                        help='optional destination directory')

    parser.add_argument('-s', '--newStrucName', type=str,
                        help="source U directory (no default)")

    parser.add_argument('-u', '--uPath', type=str,
                        help="source U directory (no default)")

    parser.add_argument('-v', '--verbose', action='store_true',
                        help='be chatty')

    args = parser.parse_args()

    # complete setup ------------------------------------------------
    appName = 'uReStruc %s' % __version__
    if args.verbose or args.justShow:
        print("%s %s" % (appName, __version_date__))

    # fixups and sanity checks --------------------------------------

    if not args.uPath or not os.path.exists(args.uPath):
        print("input directory '%s' does not exist" % args.uPath)
        parser.print_help()
        sys.exit(1)

    if not args.newStrucName or not args.newStrucName in DIR_STRUC_NAMES:
        print("you must specify a directory structure, one of %s" % DIR_STRUC_NAMES)
        parser.print_help()
        sys.exit(1)

    args.uDir = UDir.discover(args.uPath)
    args.oldStruc = args.uDir.dirStruc     # an int
    args.newStruc = nameToDirStruc(args.newStrucName)
    args.oldStrucName = dirStrucToName(args.oldStruc)

    if args.oldStrucName != args.newStrucName:
        print("restructuring from %s to %s" % (
            args.oldStrucName, args.newStrucName))
    else:
        print("retaining %s" % args.oldStrucName)

    if args.outPath and os.path.exists(args.outPath):
        print("output directory '%s' already exists" % args.outPath)
        parser.print_help()
        sys.exit(1)

    if args.verbose or args.justShow:
        print('justShow     = ' + str(args.justShow))
        print('old dirStruc = %d %s' % (args.oldStruc, args.oldStrucName))
        print('new dirStruc = %d %s' % (args.newStruc, args.newStrucName))
        print('uPath        = ' + str(args.uPath))
        print('verbose      = ' + str(args.verbose))

    if args.justShow:
        sys.exit(0)
    reStructureUDir(args)

if __name__ == '__main__':
    main()
