#!/usr/bin/env python3

"""
python/u/scripts/genNodeID1.py -- uses the contents of a subdirectory in U
to generate a 160-bit hash.  If for example U is /var/U and the
subdirectory is 'ff', then all of the files below /var/U/ff will be
walked in creating the hash.
"""

import getopt
import io
import hashlib
import re
import sys
import os
from os.path import join
from random import randint
# XXX this import does not succeed until u has been installed; need
# better understanding of search path
from xlattice.u import ULock

# DEFAULTS for command line arguments ###############################
# a random number between 00 and 0xff
SUB_DIR = str("%02x" % randint(0, 0xff))
U_DIR = '/var/U'
verbose = False

# UTILITY FUNCTIONS #################################################


def get_node_id1(sub_dir, u_dir=U_DIR):
    lock = ULock(u_dir)
    lock.get_lock()

    sha = hashlib.sha1()
    sub_dir = "%s/%s" % (u_dir, SUB_DIR)
    for root, dirs, files in os.walk(sub_dir):
        for name in files:
            abs_path = join(root, name)
            try:
                file = io.FileIO(abs_path, "r")
                reader = io.BufferedReader(file)
                while True:
                    byte_str = reader.read(io.DEFAULT_BUFFER_SIZE)
                    if len(byte_str) == 0:
                        break
                    sha.update(byte_str)
            except Exception as exc:
                print("unexpected exception reading %s: %s" % (abs_path, str(exc)))
                # otherwise we just ignore it

    lock.release_lock()
    return sha.hexdigest()        # a string

# COMMAND LINE HANDLING #############################################


def usage():
    print("usage message")

arg_vec = sys.argv[1:]
try:
    opts, args = getopt.getopt(arg_vec, "hs:u:v",
                               ["help", "sub_dir", "u_dir", "verbose"])
except getopt.GetoptError as err:
    print(str(err))
    usage()
    sys.exit(2)

for o, aVal in opts:
    if o in ('-h', '--help'):
        usage()
        sys.exit()
    elif o in ('-s', '--subDir'):
        sub_dir = aVal

    elif o in ('-v', '--verbose'):
        show_version = True
        verbose = True
    elif o in ('-u', '--uDir'):
        u_dir = aVal
    else:
        assert False, 'unhandled option'

if not re.match("^[0-9a-fA-F]{2}$", sub_dir):
    print("subDir '%s' should be a two-digit hex number" % sub_dir)
    usage()
    sys.exit()
sub_dir = sub_dir.lower()

if verbose:
    print("pid    = %u" % os.getpid())
    print("subDir = %s" % sub_dir)
    print("uDir   = %s" % u_dir)
    print('')

# notice that the order of names is odd!
node_id = get_node_id1(sub_dir, u_dir)
print(node_id)
